from __future__ import annotations

from io import BytesIO
from pathlib import Path
from typing import Mapping

import pandas as pd
import reportlab
from openpyxl.styles import Alignment, Font, PatternFill
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


NAVY = "1B4F72"
RED = "D7263D"
LIGHT = "EAF1F5"


def _register_pdf_fonts() -> None:
    """Embed ReportLab's bundled Vera fonts for consistent server-side rendering."""
    font_dir = Path(reportlab.__file__).resolve().parent / "fonts"
    fonts = {
        "AIA-Vera": "Vera.ttf",
        "AIA-Vera-Bold": "VeraBd.ttf",
        "AIA-Vera-Italic": "VeraIt.ttf",
        "AIA-Vera-BoldItalic": "VeraBI.ttf",
    }
    registered = set(pdfmetrics.getRegisteredFontNames())
    for name, filename in fonts.items():
        if name not in registered:
            pdfmetrics.registerFont(TTFont(name, str(font_dir / filename)))
    pdfmetrics.registerFontFamily(
        "AIA-Vera",
        normal="AIA-Vera",
        bold="AIA-Vera-Bold",
        italic="AIA-Vera-Italic",
        boldItalic="AIA-Vera-BoldItalic",
    )


def csv_bytes(frame: pd.DataFrame) -> bytes:
    return frame.to_csv(index=False).encode("utf-8")


def excel_report_bytes(
    frame: pd.DataFrame,
    *,
    title: str,
    filters: Mapping[str, str] | None = None,
) -> bytes:
    output = BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        frame.to_excel(writer, sheet_name="Data", index=False)
        workbook = writer.book
        sheet = writer.sheets["Data"]
        sheet.freeze_panes = "A2"
        sheet.auto_filter.ref = sheet.dimensions
        header_fill = PatternFill("solid", fgColor=NAVY)
        for cell in sheet[1]:
            cell.fill = header_fill
            cell.font = Font(color="FFFFFF", bold=True)
            cell.alignment = Alignment(wrap_text=True, vertical="center")
        sheet.row_dimensions[1].height = 34
        for column_cells in sheet.columns:
            values = [str(cell.value or "") for cell in column_cells[:100]]
            width = min(max(max(map(len, values)) + 2, 11), 34)
            sheet.column_dimensions[column_cells[0].column_letter].width = width

        meta = workbook.create_sheet("Report details", 0)
        meta["A1"] = title
        meta["A1"].font = Font(size=18, bold=True, color=NAVY)
        meta["A3"] = "Generated by"
        meta["B3"] = "AIA Canada Data Portal"
        meta["A4"] = "Source"
        meta["B4"] = "The View from Here: 2015 Productivity Benchmarks"
        row = 6
        for key, value in (filters or {}).items():
            meta.cell(row=row, column=1, value=str(key))
            meta.cell(row=row, column=2, value=str(value))
            row += 1
        for cell in meta["A"]:
            cell.font = Font(bold=True, color=NAVY)
        meta.column_dimensions["A"].width = 24
        meta.column_dimensions["B"].width = 48
    return output.getvalue()


def pdf_report_bytes(
    frame: pd.DataFrame,
    *,
    title: str,
    filters: Mapping[str, str] | None = None,
) -> bytes:
    _register_pdf_fonts()
    output = BytesIO()
    document = SimpleDocTemplate(
        output,
        pagesize=landscape(letter),
        rightMargin=0.42 * inch,
        leftMargin=0.42 * inch,
        topMargin=0.45 * inch,
        bottomMargin=0.45 * inch,
        title=title,
        author="AIA Canada",
    )
    styles = getSampleStyleSheet()
    styles["Normal"].fontName = "AIA-Vera"
    styles["BodyText"].fontName = "AIA-Vera"
    styles["Title"].fontName = "AIA-Vera-Bold"
    styles["Italic"].fontName = "AIA-Vera-Italic"
    story = [Paragraph(title, styles["Title"])]
    if filters:
        filter_line = " &nbsp; | &nbsp; ".join(
            f"<b>{key}:</b> {value}" for key, value in filters.items()
        )
        story.extend([Paragraph(filter_line, styles["BodyText"]), Spacer(1, 12)])
    story.append(Paragraph(
        "Source: AIA Canada, The View from Here: 2015 Productivity Benchmarks. "
        "Values are historical survey benchmarks and should not be interpreted as current market estimates.",
        styles["Italic"],
    ))
    story.append(Spacer(1, 12))

    printable = frame.copy()
    if len(printable.columns) > 9:
        preferred = [
            "segment", "shop_size", "geography", "affiliation", "sample_size",
            "average_repair_orders_year", "average_hours_repair_order",
            "hours_sold_technician_day", "source_page",
        ]
        printable = printable[[column for column in preferred if column in printable.columns]]
    printable = printable.fillna("—")
    rows = [[Paragraph(str(column).replace("_", " ").title(), styles["BodyText"])
             for column in printable.columns]]
    for record in printable.head(100).itertuples(index=False, name=None):
        rows.append([Paragraph(str(value), styles["BodyText"]) for value in record])
    width = 10.0 * inch / max(len(printable.columns), 1)
    table = Table(rows, repeatRows=1, colWidths=[width] * len(printable.columns))
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1B4F72")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "AIA-Vera-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "AIA-Vera"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#EAF1F5")]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#BCCAD3")),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)
    document.build(story)
    return output.getvalue()
